export const INITIALIZE_DATABASE = 'INITIALIZE_DATABASE';
export const INITIALIZE_DATABASE_SUCCESS = 'INITIALIZE_DATABASE_SUCCESS';

export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
